# https://ionic.io/ionicons
# <ion-icon name="logo-[[name]]"></ion-icon>
# name = "https://example.com/"

facebook = "https://www.facebook.com/pedroisrael.tumayC.137/"
twitter = "https://twitter.com/"
instagram = "https://www.instagram.com/israeltr.exe/"
linkedin = "https://www.linkedin.com/in/israel-tyrs-217393270/"
github = "https://github.com/EiveenL"
# figma = "figma.com/"
# youtube = "https://youtube.com/"
# reddit = "https://www.reddit.com/"
# discord = "https://discord.com/"
# pinterest = "https://www.pinterest.com/"